name: Growth

on:
  schedule:
    # UTC 时间 0 点运行一次，但是我发现一直不准，每天9点20的样子才下发（而不是原来认为的8点，晚1h20min），
    # 太晚了，我希望打开手机就已经执行，所以现在提前2h 改为 7点20的样子执行
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
          cache: 'npm'
      - name: Depend install and serve
        env:
          COOKIE: ${{ secrets.COOKIE }}
          EMAIL: ${{ secrets.EMAIL }}
          AUTHORIZATION_CODE: ${{ secrets.AUTHORIZATION_CODE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          npm ci
          npm run serve
